# Generated by Django 3.2.8 on 2021-10-21 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalHoldTime', models.IntegerField(default=0)),
                ('averageTalkTime', models.IntegerField(default=0)),
                ('totalAfterCallWorkTime', models.IntegerField(default=0)),
                ('averageAfterCallWorkTime', models.IntegerField(default=0)),
                ('totalTalkTime', models.IntegerField(default=0)),
                ('lastCallAnswerSpeed', models.IntegerField(default=0)),
                ('averageAllCallAnswerSpeed', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
